language: python
python:
    # - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "pypy"

sudo: false
os:
  - linux
  - osx
env:
  - DJANGO_PACKAGE="Django>=1.6,<1.7"
  - DJANGO_PACKAGE="Django>=1.7,<1.8"
  - DJANGO_PACKAGE="Django>=1.8,<1.9"

install:
  - pip install $DJANGO_PACKAGE --use-mirrors

script:
  - python setup.py test
# - tox -e $TOX_ENV
